server:
  port: 0
spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
management:
  endpoint:
    health:
      probes:
        enabled: true
