apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
stringData:
  db-url: jdbc:mysql://mysql/users?createDatabaseIfNotExist=true
  db-username: root
  db-password: 145spark_144g6
  jwt-key: klfjkf434jefkhebf22hjk

  clients-0-name: web-client
  clients-0-password: jfehlf34378sdr_12j1hdkl
  clients-0-grant-type: password
  clients-0-scopes-0: read
  clients-0-scopes-1: write
  clients-0-access-token-validity: "1800"
  clients-0-refresh-token-validity: "43200"

  clients-1-name: internal-client
  clients-1-password: 434_fdfdfos_355fkdfll
  clients-1-grant-type: client_credentials
  clients-1-scopes-0: read
  clients-1-scopes-1: write
  clients-1-access-token-validity: "1800"
  clients-1-refresh-token-validity: "43200"

  users-0-name: admin
  users-0-password: jkhfdjk2323766
  users-0-authority: ADMIN
    