apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    tier: ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
spec:
  ingressClassName: nginx
  rules:
    - host: ""
      http:
        paths:
          - pathType: Prefix
            path: "/users"
            backend:
              service:
                name: user-service
                port:
                  number: 4040
          - pathType: Prefix
            path: "/oauth"
            backend:
              service:
                name: auth-service
                port:
                  number: 7070
          - pathType: Prefix
            path: "/airlines"
            backend:
              service:
                name: airline-service
                port:
                  number: 5050   
          - pathType: Prefix
            path: "/flights"
            backend:
              service:
                name: airline-service
                port:
                  number: 5050     
          - pathType: Prefix
            path: "/tickets"
            backend:
              service:
                name: airline-service
                port:
                  number: 5050                         
                  