server:
  port: 5973
h2:
  console:
    enabled: true
  sql:
    init:
      platform: h2
kafka:
  bootstrapAddress: dev
  topic: dev
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  security:
    oauth2:
      jwt-key: debug-key
      client:
        client-id: debug-client
        client-secret: debug-password
        authorization-grant-type: client_credentials
        scope: read
        access-token-uri: http://localhost:49937/oauth/token
management:
  endpoint:
    health:
      probes:
        enabled: true
